### ISSUE TITLE
Setting default account creates errors

### ISSUE THREAD

**Issue by bamtan** [redsudo/RedSea#13]
```bash
./redsea.py list

ERROR: No default session has been set!

SESSIONS:
  au
  us2
  fr
  us

Please provide the name of the session you would like to set as default: au
Default session has successfully been set to "au"
Traceback (most recent call last):
  File "./redsea.py", line 147, in <module>
    main()
  File "./redsea.py", line 72, in main
    media_to_download = cli.parse_media_option(args.urls)
  File "/mnt/c/Users/bamtan/Documents/redsea/redsea/cli.py", line 64, in parse_media_option
    ci = m.index(':')
ValueError: substring not found
```

after setting default and running `readsea.py list`

```bash
./redsea.py list

Traceback (most recent call last):
  File "./redsea.py", line 147, in <module>
    main()
  File "./redsea.py", line 72, in main
    media_to_download = cli.parse_media_option(args.urls)
  File "/mnt/c/Users/bamtan/Documents/redsea/redsea/cli.py", line 64, in parse_media_option
    ci = m.index(':')
ValueError: substring not found```

**Comment by redsudo** [comment]
So this is actually a syntax error. Command should be `redsea.py auth list` (you are missing 'auth').

What is occurring is that redsea is loading, asking for a default account, then proceeding and trying to process 'list' as if it were a url instead of a command. It then errors out.

That should get you functional again. In the meantime, let's leave this open as a request for improved error handling of non-url strings.
