### ISSUE TITLE
No such file or directory: './config/sessions.pk'

### ISSUE THREAD

**Issue by HaskDev0** [redsudo/RedSea#36]
When trying to download a track from urls via:
$ python3 redsea.py urls
it throws such a message:
Traceback (most recent call last):
  File "/Users/{user_name}/Downloads/RedSea-master/redsea.py", line 225, in <module>
    main()
  File "/Users/{user_name}/Downloads/RedSea-master/redsea.py", line 36, in main
    RSF = RedseaSessionFile('./config/sessions.pk')
  File "/Users/{user_name}/Downloads/RedSea-master/redsea/tidal_api.py", line 179, in __init__
    self._save()
  File "/Users/{user_name}/Downloads/RedSea-master/redsea/tidal_api.py", line 191, in _save
    with open(self.session_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './config/sessions.pk'

How to fix this error?

**Comment by redsudo** [comment]
Oh good catch. I forgot to add account set up instructions to the installation docs.

Just run `redsea.py auth add` and follow the prompts

**Comment by HaskDev0** [comment]
@redsudo , unfortunately, this command also throws the same error:
FileNotFoundError: [Errno 2] No such file or directory: ‘./config/sessions.pk’

Am I doing smth wrong?

**Comment by redsudo** [comment]
I just tested this on both the master and develop branches and cannot reproduce. Which version of redsea are you using? (I tested with release 2.0.0) Have you made sure you are up to date with either the latest release or current state of the master branch?

**Comment by redsudo** [comment]
Closing since no activity. Please re-open if this resurfaces
