### ISSUE TITLE
crypto package issue

### ISSUE THREAD

**Issue by IR7777** [redsudo/RedSea#53]
all of a sudden i'm getting crypto package issues:

Traceback (most recent call last):
  File "redsea.py", line 7, in <module>
    from redsea.mediadownloader import MediaDownloader
  File "/Users/Music/RedSea1/RedSea-master/redsea/mediadownloader.py", line 10, in <module>
    from .decryption import decrypt_file, decrypt_security_token
  File "/Users/Music/RedSea1/RedSea-master/redsea/decryption.py", line 3, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

any advice on how that happened? tool was working for months without any issue.

**Comment by alexandrox** [comment]
Ihave the same problem, if I install Cryptodome 3.9.7 i don't have any issue, but 3.9.0 show this:

  ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\*******\\AppData\\Local\\Temp\\pip-install-g9wwuf7m\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\*******\\AppData\\Local\\Temp\\pip-install-g9wwuf7m\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\*******\AppData\Local\Temp\pip-install-g9wwuf7m\pycryptodome\pip-egg-info'
         cwd: C:\Users\*******\AppData\Local\Temp\pip-install-g9wwuf7m\pycryptodome\
    Complete output (31 lines):
    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\*******\AppData\Local\Temp\pip-install-g9wwuf7m\pycryptodome\setup.py", line 448, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\*******\AppData\Local\Temp\pip-install-g9wwuf7m\pycryptodome\compiler_opt.py", line 304, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\*******\AppData\Local\Temp\pip-install-g9wwuf7m\pycryptodome\compiler_opt.py", line 239, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\*******\AppData\Local\Temp\pip-install-g9wwuf7m\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alexandrox** [comment]
I installed Crypto package whith pip install and this update to Cryptodome 3.9.7. I resolved my issue finally
