### ISSUE TITLE
I can't download

### ISSUE THREAD

**Issue by pintyoke** [redsudo/RedSea#57]
I could download it before yesterday, not today. :(

" Asset is not ready for playback (HTTP 401)
Stream could not be acquired
Skipping track..."

**Comment by pintyoke** [comment]
Change the token hash in tidal_api.py

old token = '4zx46pyr9o8qZNRw'
new  token = 'u5qPNNYIbD0S0o36MrAiFZ56K6qMCrCmYPzZuTnV'

**Comment by moonraker2** [comment]
[tidal_api.zip](https://github.com/redsudo/RedSea/files/4309268/tidal_api.zip)

@pintyoke 
I tried replacing the token string you mention with the new value everywhere it showed up in tidal_api.py (3 occurrences) but in my case this does not work, I now get syntax error:

Traceback (most recent call last):
  File "redsea.py", line 7, in <module>
    from redsea.mediadownloader import MediaDownloader
  File "/home/soren/RedSea/redsea/mediadownloader.py", line 12, in <module>
    from .tidal_api import TidalApi, TidalRequestError
  File "/home/soren/RedSea/redsea/tidal_api.py", line 97
    self.unique_id = str(uuid.uuid4()).replace('-', '')[16:]f
                                                                                    ^
SyntaxError: invalid syntax

Did you replace it everywhere or no?

Attached my copy of the tidal_api.py file for reference.

**Comment by moonraker2** [comment]
Tried deleting the trailing "f" in line as referred above, but then I'm just back to the error with which it started out:

Grabbing stream URL...
	4005: Asset is not ready for playback (HTTP 401)
	Stream could not be acquired
Halting on track <omitted> due to insufficient quality

**Comment by moonraker2** [comment]
I created a new auth session after making above changes, by doing "python3 redsea.py auth add" and now it seems to be working again.

**Comment by stephanlensky** [comment]
> Change the token hash in tidal_api.py
> 
> old token = '4zx46pyr9o8qZNRw'
> new token = 'u5qPNNYIbD0S0o36MrAiFZ56K6qMCrCmYPzZuTnV'

@pintyoke Where did you find the new token? just out of curiosity :)
