### ISSUE TITLE
AttributeError: 'MP4Tags' object has no attribute '_padding'. Problem with certain tracks.

### ISSUE THREAD

**Issue by Bredkov** [redsudo/RedSea#61]
Here is a log of a problem with 2 tracks ...

c:\RedSea>redsea.py -p best_available https://tidal.com/album/130812394

 /$$$$$$$                  /$$  /$$$$$$
| $$__  $$                | $$ /$$__  $$
| $$  \ $$  /$$$$$$   /$$$$$$$| $$  \__/  /$$$$$$   /$$$$$$
| $$$$$$$/ /$$__  $$ /$$__  $$|  $$$$$$  /$$__  $$ |____  $$
| $$__  $$| $$$$$$$$| $$  | $$ \____  $$| $$$$$$$$  /$$$$$$$
| $$  \ $$| $$_____/| $$  | $$ /$$  \ $$| $$_____/ /$$__  $$
| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$/|  $$$$$$$|  $$$$$$$
|__/  |__/ \_______/ \_______/ \______/  \_______/ \_______/

                    (c) 2016 Joe Thatcher
               https://github.com/svbnet/RedSea

<<< Downloading single track... >>>
=== Downloading track ID 130812395 ===
        Track: 01
        Title: Take a Bite
        Artist: Flight Paths
        Album: Take a Bite
        ----
        Grabbing stream URL...
        Download progress: 100%
        Downloading album art...
        Download progress: 100%
        Tagging media file...
Traceback (most recent call last):
  File "C:\RedSea\redsea.py", line 225, in <module>
    main()
  File "C:\RedSea\redsea.py", line 169, in main
    md.download_media(track, preset['quality'], media_info)
  File "C:\RedSea\redsea\mediadownloader.py", line 195, in download_media
    self.tm.tag_m4a(temp_file, track_info, album_info, aa_location)
  File "C:\RedSea\redsea\tagger.py", line 107, in tag_m4a
    self._meta_tag(tagger, track_info, album_info, 'm4a')
  File "C:\RedSea\redsea\tagger.py", line 84, in _meta_tag
    self.tags(track_info, track_type, album_info, tagger)
  File "C:\RedSea\redsea\tagger.py", line 44, in tags
    tagger['artist'] = track_info['artist']['name']
  File "C:\Users\bredk\AppData\Local\Programs\Python\Python35\lib\site-packages\mutagen\_file.py", line 66, in __setitem__
    self.add_tags()
  File "C:\Users\bredk\AppData\Local\Programs\Python\Python35\lib\site-packages\mutagen\mp4\__init__.py", line 995, in add_tags
    self.tags = self.MP4Tags()
  File "C:\Users\bredk\AppData\Local\Programs\Python\Python35\lib\site-packages\mutagen\easymp4.py", line 43, in __init__
    self._padding = self.__mp4._padding
AttributeError: 'MP4Tags' object has no attribute '_padding'

c:\RedSea>redsea.py -p best_available https://tidal.com/album/138942100

 /$$$$$$$                  /$$  /$$$$$$
| $$__  $$                | $$ /$$__  $$
| $$  \ $$  /$$$$$$   /$$$$$$$| $$  \__/  /$$$$$$   /$$$$$$
| $$$$$$$/ /$$__  $$ /$$__  $$|  $$$$$$  /$$__  $$ |____  $$
| $$__  $$| $$$$$$$$| $$  | $$ \____  $$| $$$$$$$$  /$$$$$$$
| $$  \ $$| $$_____/| $$  | $$ /$$  \ $$| $$_____/ /$$__  $$
| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$/|  $$$$$$$|  $$$$$$$
|__/  |__/ \_______/ \_______/ \______/  \_______/ \_______/

                    (c) 2016 Joe Thatcher
               https://github.com/svbnet/RedSea

<<< Downloading single track... >>>
=== Downloading track ID 138942101 ===
        Track: 01
        Title: Washed Away Reimagined
        Artist: Flight Paths
        Album: Washed Away Reimagined
        ----
        Grabbing stream URL...
        Download progress: 100%
        Downloading album art...
        Download progress: 100%
        Tagging media file...
Traceback (most recent call last):
  File "C:\RedSea\redsea.py", line 225, in <module>
    main()
  File "C:\RedSea\redsea.py", line 169, in main
    md.download_media(track, preset['quality'], media_info)
  File "C:\RedSea\redsea\mediadownloader.py", line 195, in download_media
    self.tm.tag_m4a(temp_file, track_info, album_info, aa_location)
  File "C:\RedSea\redsea\tagger.py", line 107, in tag_m4a
    self._meta_tag(tagger, track_info, album_info, 'm4a')
  File "C:\RedSea\redsea\tagger.py", line 84, in _meta_tag
    self.tags(track_info, track_type, album_info, tagger)
  File "C:\RedSea\redsea\tagger.py", line 44, in tags
    tagger['artist'] = track_info['artist']['name']
  File "C:\Users\bredk\AppData\Local\Programs\Python\Python35\lib\site-packages\mutagen\_file.py", line 66, in __setitem__
    self.add_tags()
  File "C:\Users\bredk\AppData\Local\Programs\Python\Python35\lib\site-packages\mutagen\mp4\__init__.py", line 995, in add_tags
    self.tags = self.MP4Tags()
  File "C:\Users\bredk\AppData\Local\Programs\Python\Python35\lib\site-packages\mutagen\easymp4.py", line 43, in __init__
    self._padding = self.__mp4._padding
AttributeError: 'MP4Tags' object has no attribute '_padding'

**Comment by alexandrox** [comment]
![imagen](https://user-images.githubusercontent.com/12411684/82363887-16a12f00-99d4-11ea-840e-27b0d00521bb.png)
It's the token, if you use a mobile token only download in mp4a (ALAC / ACC), chanche this and create a new account (login again) `py redsea.py -a` using the new token

**Comment by Bredkov** [comment]
I can't understand. Why it happens only with certain albums? I still can download in FLAC.

**Comment by Bredkov** [comment]
Ok. Works well. Token MbjR4DLXz1ghC4rV
