### ISSUE TITLE
Auth broken

### ISSUE THREAD

**Issue by Bredkov** [redsudo/RedSea#65]
today recive this message:

Traceback (most recent call last):
  File "C:\RedSea\redsea.py", line 225, in <module>
    main()
  File "C:\RedSea\redsea.py", line 60, in main
    RSF.reauth()
  File "C:\RedSea\redsea\sessions.py", line 178, in reauth
    raise(e)
  File "C:\RedSea\redsea\sessions.py", line 167, in reauth
    session.auth(password)
  File "C:\RedSea\redsea\tidal_api.py", line 138, in auth
    raise TidalRequestError(r)
redsea.tidal_api.TidalRequestError: 3009: None (HTTP 401)

Tryied reauth. Failed. Removed it. Tryed to auth again. Failed.

**Comment by Bredkov** [comment]
Token MbjR4DLXz1ghC4rV

**Comment by Bredkov** [comment]
Geting token using this link doesn't help.
https://github.com/lucaslg26/TidalAPI

**Comment by pintyoke** [comment]
New token: wc8j_yBJd20zOmx0

**Comment by Bredkov** [comment]
> New token: wc8j_yBJd20zOmx0

Thank you! Works well! Is there any way to get token on Windows? Link up here doesn't work =(

**Comment by pintyoke** [comment]
Sorry, I don't know.

> 
> 
> > New token: wc8j_yBJd20zOmx0
> 
> Thank you! Works well! Is there any way to get token on Windows? Link up here doesn't work =(

**Comment by IR7777** [comment]
> New token: wc8j_yBJd20zOmx0

looks like the token is dead :(

**Comment by IR7777** [comment]
> New token: wc8j_yBJd20zOmx0

@pintyoke how do you get these, can you share?  i tried the fiddler method but like referenced above it doesn't work, well i can get the token out of fidler but putting it into redsea doesn't work.

**Comment by Bredkov** [comment]
Can some one post a new token?
